[workspace]

members = [
    "api",
    "models",
    "bank",
    "utils",
    "xerror",
    "msgs",
    "core_types",
    "lnd_connector",
    "dealer",
    "kollider_hedging",
    "ws_client",
    "cli",
]